name: Deployment

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint and test
        run: |
          echo "lint-and-test success"

  deploy-to-artifact-repository:
    if: github.event_name == 'push'
    needs: lint-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v3

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker asia-northeast3-docker.pkg.dev --quiet

      - name: Build Docker image
        run: |
          docker build \
            -t asia-northeast3-docker.pkg.dev/project-ec088c24-d2f6-4ac3-bbf/mlops-quicklab/trainer:${{ github.sha }} \
            vertexai/predictions

      - name: Push Docker image
        run: |
          docker push \
            asia-northeast3-docker.pkg.dev/project-ec088c24-d2f6-4ac3-bbf/mlops-quicklab/trainer:${{ github.sha }}