name: Deployment

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint and test
        run: |
          echo "lint-and-test success"

  deploy-to-artifact-repository:
    if: github.event_name == 'push'
    needs: lint-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Artifact Registry test
        run: |
          echo "deploy-to-artifact-repository success"

  deploy-to-vertex-ai:
    if: github.event_name == 'push'
    needs: deploy-to-artifact-repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Vertex AI test
        run: |
          echo "deploy-to-vertex-ai success"